name: Homebrew bump cask
description: Bump (update) a Homebrew cask on new project release
author: macauley
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: GitHub token (not the default one)
    required: true
  message:
    description: |
      Additional message to append to created PR.
    required: false
  org:
    description: |
      Fork tap repository to selected GitHub organization.
    required: false
  tap:
    description: |
      Cask tap.

      In livecheck mode, if cask input is empty,
      the Action will check the whole tap.

      Example: dawidd6/tap
      Example: dawidd6/homebrew-tap
    required: false
  cask:
    description: |
      Cask name.

      In livecheck mode, this could take more than one cask,
      separated by commas or spaces or newlines.

      Example: macloggerdx
      Example (livecheck): macloggerdx, wsjtx
    required: false
  tag:
    description: |
      Git tag.

      It is determined automatically.

      Example: v1.0.0
      Example: refs/tags/v1.0.0
    required: false
    default: ${{github.ref}}
  revision:
    description: |
      Git revision.

      Only required for cask that use git to download the source.

      It is determined automatically.

      Example: 130d3a3af72f66780ae4e24cd143ae7a4d757f9d
    required: false
    default: ${{github.sha}}
  force:
    description: Check open PRs or not (will fail if detected)
    required: false
  livecheck:
    description: |
      Use `brew livecheck` to determine outdated casks.

      If tap input is specified - check all cask in this tap.
      If cask input is specified - check one or more casks.
      If cask and tap inputs are specified - check one or more casks in that tap.
    required: false
  dryrun:
    description: Pass --dry-run to `brew bump-cask-pr`
    required: false

runs:
  using: composite
  steps:
    - run: echo /home/linuxbrew/.linuxbrew/bin >> $GITHUB_PATH
      shell: sh
    - run: brew update-reset
      shell: sh
    - run: brew ruby $GITHUB_ACTION_PATH/main.rb
      shell: sh
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{inputs.token}}
        HOMEBREW_BUMP_MESSAGE: ${{inputs.message}}
        HOMEBREW_BUMP_ORG: ${{inputs.org}}
        HOMEBREW_BUMP_TAP: ${{inputs.tap}}
        HOMEBREW_BUMP_CASK: ${{inputs.cask}}
        HOMEBREW_BUMP_TAG: ${{inputs.tag}}
        HOMEBREW_BUMP_REVISION: ${{inputs.revision}}
        HOMEBREW_BUMP_FORCE: ${{inputs.force}}
        HOMEBREW_BUMP_LIVECHECK: ${{inputs.livecheck}}
        HOMEBREW_BUMP_DRYRUN: ${{inputs.dryrun}}
